stages:
  - docker-build

services:
  - docker:19.03.12-dind
docker-build:
  stage: docker-build
  image:
    name: docker:19.03.12
  script:
    - |
      docker login -u "${DOCKERHUB_USERNAME}" -p "${DOCKERHUB_PASSWORD}"
      docker buIld -t primeframe-bot .
