stages:
  - docker-build

services:
  - docker:19.03.12-dind
docker-build:
  stage: docker-build
  image:
    name: docker:19.03.12
  script:
    - |
      docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      docker build -t dshlab/primeframe-bot:$CI_COMMIT_SHORT_SHA dshlab/primeframe-bot:latest
      docker push dshlab/primeframe-bot:$CI_COMMIT_SHORT_SHA
      docker push dshlab/primeframe-bot:latest
